### ISSUE TITLE
Config parsing fails if field has '%' in it

### ISSUE THREAD

**Issue by Rycieos** [gpailler/AtlassianBot#16]
Updated my JIRA password, and discovered that the bot would no longer load. Seems to crash on the '%' character:
```yaml
jira:
    ...
    password: examplepassword%
```
```
[04/17/2018 14:09:39] | slackbot.manager | ERROR | Failed to import plugins.stash
Apr 17 14:09:39 jaguar python[11786]: Traceback (most recent call last):
Apr 17 14:09:39 jaguar python[11786]: File "/opt/slack/venv/lib/python3.4/site-packages/slackbot/manager.py", line 60, in _load_plugins
Apr 17 14:09:39 jaguar python[11786]: import_module(module)
Apr 17 14:09:39 jaguar python[11786]: File "/opt/slack/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
Apr 17 14:09:39 jaguar python[11786]: return _bootstrap._gcd_import(name[level:], package, level)
Apr 17 14:09:39 jaguar python[11786]: File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
Apr 17 14:09:39 jaguar python[11786]: File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
Apr 17 14:09:39 jaguar python[11786]: File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
Apr 17 14:09:39 jaguar python[11786]: File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
Apr 17 14:09:39 jaguar python[11786]: File "<frozen importlib._bootstrap>", line 1129, in _exec
Apr 17 14:09:39 jaguar python[11786]: File "<frozen importlib._bootstrap>", line 1471, in exec_module
Apr 17 14:09:39 jaguar python[11786]: File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
Apr 17 14:09:39 jaguar python[11786]: File "/opt/slack/AtlassianBot/plugins/stash.py", line 4, in <module>
Apr 17 14:09:39 jaguar python[11786]: from utils import rest
Apr 17 14:09:39 jaguar python[11786]: File "/opt/slack/AtlassianBot/utils/rest.py", line 3, in <module>
Apr 17 14:09:39 jaguar python[11786]: import plugins.settings as settings
Apr 17 14:09:39 jaguar python[11786]: File "/opt/slack/AtlassianBot/plugins/settings.py", line 8, in <module>
Apr 17 14:09:39 jaguar python[11786]: config = Configuration.from_file(current_dir + '/settings.yml').configure()
Apr 17 14:09:39 jaguar python[11786]: File "/opt/slack/venv/src/configure-master/configure.py", line 204, in from_file
Apr 17 14:09:39 jaguar python[11786]: configure=configure)
Apr 17 14:09:39 jaguar python[11786]: File "/opt/slack/venv/src/configure-master/configure.py", line 221, in from_string
Apr 17 14:09:39 jaguar python[11786]: string = string % ctx
Apr 17 14:09:39 jaguar python[11786]: ValueError: unsupported format character '?' (0xa) at index 5658
```

Trying to wrap the string in quotes as suggested by the YAML spec also doesn't work, though crashes on a different character:
```yaml
    password: "examplepassword%"
or
    password: 'examplepassword%'
```
```
Apr 17 14:10:38 jaguar python[11786]: ValueError: unsupported format character '"' (0x22) at index 5659
or
Apr 17 14:11:43 jaguar python[11786]: ValueError: unsupported format character ''' (0x22) at index 5659
```

This seems to be the issue here:
https://github.com/alfred82santa/configure/blob/173ea9b4257a988dd0df604505a09b6778d9df54/configure.py#L221

Obviously this is a dependency, but the development of that library seems dead, and there is no way to report an issue for that repo.

**Comment by gpailler** [comment]
Thanks for this feedback.
Yes this dependency looks unmaintained since long time. I probably have to find another Yaml parser library (I think I took this one because this lib was able to use variables in YAML)

**Comment by gpailler** [comment]
@Rycieos 
Could you try the branch 16-YamlParsing or simply apply the commit e7ed6172f5b0c44560b7906089dd78892bd00a15 to confirm the issue is fixed?

Thanks

**Comment by Rycieos** [comment]
The config loading seems to be working, but when running the app or tests, it crashes with `AttributeError: 'AttrMap' instance has no attribute 'imageproxy'`:
```
$ py.test
================================================= test session starts =================================================
platform linux -- Python 3.4.6, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /opt/slack/AtlassianBot, inifile:
plugins: flask-0.10.0
collected 50 items / 3 errors

======================================================= ERRORS ========================================================
________________________________________ ERROR collecting tests/test_clean.py _________________________________________
tests/test_clean.py:6: in <module>
    from plugins.clean import CleanBot
plugins/clean.py:12: in <module>
    from . import jira
plugins/jira.py:312: in <module>
    settings.servers.imageproxy,
../venv/lib/python3.4/site-packages/attrdict/mixins.py:82: in __getattr__
    cls=self.__class__.__name__, name=key
E   AttributeError: 'AttrMap' instance has no attribute 'imageproxy'
___________________________________ ERROR collecting tests/test_imageproxy_flask.py ___________________________________
ImportError while importing test module '/opt/slack/AtlassianBot/tests/test_imageproxy_flask.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../venv/lib/python3.4/site-packages/wand/api.py:180: in <module>
    libraries = load_library()
../venv/lib/python3.4/site-packages/wand/api.py:135: in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
E   OSError: cannot find library; tried paths: []

During handling of the above exception, another exception occurred:
tests/test_imageproxy_flask.py:2: in <module>
    import imageproxy.flask_app
imageproxy/flask_app.py:3: in <module>
    import wand.image
../venv/lib/python3.4/site-packages/wand/image.py:20: in <module>
    from .api import MagickPixelPacket, libc, libmagick, library
../venv/lib/python3.4/site-packages/wand/api.py:206: in <module>
    'Try to install:\n  ' + msg)
E   ImportError: MagickWand shared library not found.
E   You probably had not installed ImageMagick library.
E   Try to install:
E     http://docs.wand-py.org/en/latest/guide/install.html
_________________________________________ ERROR collecting tests/test_jira.py _________________________________________
tests/test_jira.py:10: in <module>
    from plugins.jira import JiraBot, JiraNotifierBot
plugins/jira.py:312: in <module>
    settings.servers.imageproxy,
../venv/lib/python3.4/site-packages/attrdict/mixins.py:82: in __getattr__
    cls=self.__class__.__name__, name=key
E   AttributeError: 'AttrMap' instance has no attribute 'imageproxy'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 3 error in 1.16 seconds ===============================================
```
I made sure to install `requirements.txt` again to get the new package.

**Comment by Rycieos** [comment]
While testing, I ran the tests on `master`, and found that the exact same issues were there too. I tried running the app, and found that the whole app doesn't actually crash, but the JIRA plugin doesn't work, only Crucible is working right now.

**Comment by gpailler** [comment]
Do you have the imageproxy section in your settings.yml file?
(like in this https://github.com/gpailler/AtlassianBot/blob/master/plugins/settings-sample.yml)

The imageproxy is used by Jira plugin to display proper bugs/stories icons and needs ImageMagick dependency. You can find details about how to install ImageMagick for python wand module on http://docs.wand-py.org/en/latest/guide/install.html

**Comment by Rycieos** [comment]
Ah, I missed commit bcc503a6b0327cfa77a88f9068f61f57b5114eb8 which moved the `imageproxy` section from under `jira`. Thanks for pointing that out.

When I copied that section to my config, those tests pass, and the server runs. I can now work the bot normally. The patch works for me!

Thanks for the fast turn around on this!

**Comment by gpailler** [comment]
Ok thanks for the feedback. I will merge the branch.
